# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

image:
- Visual Studio 2017

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "12"

matrix:
  fast_finish: true

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version

cache:
  - node_modules -> package.json

before_test:
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Run tests
  - npm run eslint
  - npm run test-cov

after_test:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
